Add missing limits.h include
Fixes build with musl libc that does not include limits.h indirectly via
other headers.

evtest.c: In function ‘scan_devices’:
evtest.c:886:14: error: ‘PATH_MAX’ undeclared (first use in this function); did you mean  INT8_MAX’?
   char fname[PATH_MAX];
              ^~~~~~~~

Signed-off-by: Baruch Siach <baruch@tkos.co.il>
Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>